### ISSUE TITLE
SGC action points

### ISSUE THREAD

**Issue by des-des** [foundersandcoders/nazareth-curriculum#10]
## [Week 1](https://github.com/foundersandcoders/nazareth-curriculum/blob/master/stop-go-continue/fac-n1/week1.md)

 - [x] start at 10am
 - [x] get ask for git flow card to be brought https://github.com/foundersandcoders/nazareth-programme/issues/89 @mcelearr ? (jbarget: the cards couldn't be found)
 - [x] get bin
 - [x] fix squeeky chairs @Jbarget 
 - [x] add more specific subpoints to learning outcomes 
 - [x] add prerequisites to morning challenges and workshops https://github.com/foundersandcoders/master-reference/issues/175

**Comment by Jbarget** [comment]
## Week 2

**Comment by Jbarget** [comment]
## Week 3

**Comment by Jbarget** [comment]
## [Week 4](https://github.com/foundersandcoders/nazareth-curriculum/blob/master/stop-go-continue/fac-n1/week4.md)

 - [ ] On day 5 laptops closed after lunch and projector showing learning outcomes/timetable from the week @des-des 
 - [ ] Open issue to name the two SCG consistently (cohort wide v team wide) @des-des 
 - [ ] Open issue to against week 4 to better contextualise the week by giving real world examples of node @des-des 
-  [ ] Use projector screen next week (see if it works well or not) @des-des 
-  [ ] Organise mentor project for Day 5 @des-des

**Comment by m4v15** [comment]
## Week 5

- [ ]  No laptops during SGC, stand around and throw a ball
- [ ]  Lubes will bring his balls to SGC @mattlub 
- [ ]  Re-assess at node week 2 project to possibly make more interesting @des-des 
- [ ]  Encourage, but don't enforce, use of emoji's in issues/general
- [ ]  Students should ask mentors after a workshop if they can make something for walls
- [ ]  A mentor gives us all a brief run down of them at the start of next week's biz-dev @des-des 
- [ ]  Make sure we are all aware of that the minutes/AP's are here @foundersandcoders/facn1 
- [ ]  Move the ladder back to the GH and bring a pointer for little old Eoin @RQ16 
- [ ]  Move arabic lessons to Sundays @Suuuuha 
- [ ]  Jack will write learning outcomes on the wall next week @JWLD 
- [ ]  Students work off the master reference if in doubt, mentors keep in touch of any change we might not be away of. 
- [ ]  We will create a note's folder on Naz Curriculum that we can all update with our solutions to the Workshops to refer to. Elias has one that might be helpful. @macintoshhelper

**Comment by shiryz** [comment]
@des-des happy to close this one?

**Comment by des-des** [comment]
:man_dancing:
