### ISSUE TITLE
West Bank tour info

### ISSUE THREAD

**Issue by des-des** [foundersandcoders/nazareth-curriculum#12]
Students will need to budget for meals and entrance fees to attractions, though they can opt not to have a tour guide if they would prefer not to.

Please find below suggested tour program and rates for weekend in Jerusalem from 24—26/March 2017.
 
Program:
24/March – Friday: Leave Nazareth, drive to Jerusalem through Jordan Valley, on the way stop at Jericho the oldest city in the world, proceed to Qumran, the site where the Dead Sea scrolls were discovered. Continue to Dead Sea (420 meters below sea level) for a floating experience. Drive to your hotel in Bethlehem for overnight.
 
25/March – Saturday: Drive to the Mount of Olives. Where you will enjoy the 'breath taking' view over the Holy City of Jerusalem. From there we descend to visit the Church of All Nations and the Garden of Gethsemane.
We will walk the via of the Cross 'Via Dolorosa', Church of the Flagellation and the Church of the Holy Sepulcher. We continue to the Cardo, the Roman main street of the Old City via the Jewish quarter and back to the coach.
Return to your hotel for overnight stay.
 
26/March – Sunday: After breakfast, Drive to Bethlehem, to visit the Church of the Nativity and the Shepard's Fields. Proceed to Jerusalem enter old city via the Dung Gate to visit the Wailing Wall and the Temple Mount.  Proceed to Mount Zion to visit the Cenacle – the Last Supper Room, King David's Tomb and The Dormition Abbey.  We drive then via the western new city of Jerusalem, observe the Hebrew University, the Parliament House and the Supreme Court. Drive to Ein Karem to visit the Church of the Visitation and John the Baptist's birth place. Drive back to Nazareth.  
 

Afifi Group is generously sponsoring the hotel and transportation.
2 Nights accommodation at Paradise Hotel – Bethlehem on B/B basis.
All ground transportation as per suggested itinerary
 
This excludes:
Lunches, dinners and beverages
Medical insurance
Personal expenses and tips
Entrance fees to all sites and tourists attractions as per suggested itinerary
English speaking guide throughout the tour
 
However, if the students want a tour guide and to enter places then these are the rates that will be paid by them,
Guide – 3 full days plus Saturday supplement with discount $890, 45$ per person
Entrance fees to Tel Jericho & Qumran $15 per person
Which the total sum will be 60$ (225 shekels ) per person.
 
Above offer is based on minimum 20.pax, in case number of participants changed, rate will be revised accordingly.
Hope the above is clear and ok by you, for further assistance please do not hesitate to contact me. Please advise if to book, and how many will attend and with whom they are going to share a room.

**Comment by des-des** [comment]
Please leave a comment below with two pieces of info.

1. Can you attend?
2. Would you like a tour guide?

**Comment by m4v15** [comment]
1. Yes
2. No, but if everyone else does will do.

What's the "above rate" that is referred to?

**Comment by edgarfinn** [comment]
1. Yes!
2. Reckon so, I'm easy.

**Comment by SavageWilliam** [comment]
1. Yes
2. If possible a guide for certain aspects could be awesome. But from start-to-finish probs not

**Comment by des-des** [comment]
Updated with some money info

**Comment by iteles** [comment]
Nice!

**Comment by macintoshhelper** [comment]
1. Yes
2. No, would prefer without one

**Comment by esraajb** [comment]
yes
no

**Comment by philawsophizing** [comment]
1. Yes
2. Either way really. Start to finish might be a bit much

**Comment by JMurphyWeb** [comment]
1. Definitely
2. Think a guide would be really nice for parts of the trip (Jerusalem??)

@des-des I don't understand how this trip works without a guide of sorts? Do we have a minibus and driver or is it on busses and just a recommended itinerary?

**Comment by Karyum** [comment]
yes
no

**Comment by mattlub** [comment]
yes
yes for at least part of it if poss

**Comment by JWLD** [comment]
Yes
Maybe for some of it

**Comment by emilyb7** [comment]
i'm in!
not too bothered about the tour guide...

**Comment by rebeccaradding** [comment]
Closing as this trip already happened!

**Comment by des-des** [comment]
:taco:
