### ISSUE TITLE
two "week 13" retrospectives

### ISSUE THREAD

**Issue by jsms90** [foundersandcoders/nazareth-curriculum#31]
+ [the week Noga and Esraa delivered](https://github.com/foundersandcoders/nazareth-curriculum/blob/master/stop-go-continue/fac-n1/week13.md)
+ [the week I was in Nazareth](https://github.com/foundersandcoders/nazareth-curriculum/blob/master/stop-go-continue/fac-n1/week-13.md)

@esraajb Could you update the name(s) to reflect whichever weeks they should be called?

**Comment by esraajb** [comment]
done 👍

**Comment by jsms90** [comment]
No PR? :scream: 
Life just got so much easier :flushed:

**Comment by m4v15** [comment]
@jsms90 can this be closed?
