### ISSUE TITLE
C4e launch

### ISSUE THREAD

**Issue by des-des** [foundersandcoders/nazareth-curriculum#8]
- [x] confirm start date: **monday 6th** 
 - [ ] build ad @nogainbar
 - [ ] build mentor schedule @des-des
 - [ ] send out ad + do promo @esraajb 

Okay we need to get going on this, not really sure what parts of this I am responsible for but I realise that we need movement!

**Comment by esraajb** [comment]
6th its.

we are waiting for samer to build the ad.

**Comment by rebeccaradding** [comment]
@des-des I'm confused about where this discussion should be, in nazareth-programme or here? I just posted comments over there.

**Comment by des-des** [comment]
Yes it should prob be there. Who is responsible for chasing up about the ad?

**Comment by des-des** [comment]
Moving discussion to here: https://github.com/foundersandcoders/nazareth-programme/issues/38
